### PR TITLE
Upgrade to Timex 2.1.0

### PR DESCRIPTION
**Pull request by rpip**
I have updated Timex to 2.1.0 and made the necessary changes. All the tests passed. 

Please look into this and see if it's something you can merge because this library is very useful!

Cheers,

### CODE REVIEW

**Comment by mneudert** [comment]
Could you change that to require only "~> 2.0" of timex? As far as features used it should not break just matching the major version and at the same time be not too restrictive to cause problems.

I tried that some days ago and think it worked fine but didn't make the change because the new version was, well, new back then :D

But as time passed it should be fine to make the switch and have a new release out afterwards...

**Comment by mneudert** [comment]
To make things easier I just made a [separate branch](https://github.com/mneudert/plug_accesslog/tree/timex-2.0) with an update to your patch.

Just removed the usages of the now deprecated time atoms (`:secs`, `:usecs`, ...) while keeping you as the author of the commit.

If you are fine with that I would merge that branch as a replacement including the additions to `CHANGELOG.md` and `README.md` I added.

**Comment by rpip** [comment]
Cool, so we still get the Timex upgrade but with a relaxed version requirement :)

:+1:

**Comment by mneudert** [comment]
As you may have noticed I merged the changes :heart: :yellow_heart: :blue_heart: :green_heart: :purple_heart: 

Planning to release a new library version tomorrow if nothing goes horribly wrong.

**Pull request closed without merging**
